# The URL the site will be built for
base_url = "https://www.deskonauci.pl"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

render_emoji = true



[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here
title = "Szkoła Deskonautów"
name = "Deskonauci"

[[ extra.menu ]]
name = "Instruktorzy"
icon = "fa fa-user"
path = "#team"
weight = 10

[[ extra.menu ]]
name = "Gdzie Uczymy"
icon = "fa fa-map-marker"
path = "#where"
weight = 20

[[ extra.menu ]]
name = "Oświadczenie"
icon = "fa fa-file-text"
path = "files/Oswiadczenie-szkolka-deskorolkowa.pdf"
weight = 30

[[ extra.menu ]]
name = "Cennik"
icon = "fa fa-money"
path = "#pricing"
weight = 40

[[ extra.team ]]
title = "CEO"
name = "Gutek"
path = "gutek.png"
description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore."
weight = 30
